if [ ! "$_fasttext_INCLUDED_" = "1" ]; then
_fasttext_INCLUDED_=1


feature_fasttext() {
	FEAT_NAME=fasttext
	FEAT_LIST_SCHEMA="SNAPSHOT:source 0_1_0:source"
	FEAT_DEFAULT_ARCH=
	FEAT_DEFAULT_FLAVOUR=source
}


feature_fasttext_0_1_0() {
	FEAT_VERSION=0_1_0
	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL="https://github.com/facebookresearch/fastText/archive/v0.1.0.tar.gz"
	FEAT_SOURCE_URL_FILENAME="fasttext-v0.1.0.tar.gz"
	FEAT_SOURCE_URL_PROTOCOL=HTTP_ZIP

	FEAT_BINARY_URL=
	FEAT_BINARY_URL_FILENAME=
	FEAT_BINARY_URL_PROTOCOL=

	FEAT_SOURCE_CALLBACK=
	FEAT_BINARY_CALLBACK=
	FEAT_ENV_CALLBACK=

	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT/fasttext"
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"

}

feature_fasttext_SNAPSHOT() {
	FEAT_VERSION=SNAPSHOT
	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL=https://github.com/facebookresearch/fastText
	FEAT_SOURCE_URL_FILENAME=
	FEAT_SOURCE_URL_PROTOCOL=GIT

	FEAT_BINARY_URL=
	FEAT_BINARY_URL_FILENAME=
	FEAT_BINARY_URL_PROTOCOL=

	FEAT_SOURCE_CALLBACK=
	FEAT_BINARY_CALLBACK=
	FEAT_ENV_CALLBACK=

	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT/fasttext"
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"

}

feature_fasttext_install_source() {
	INSTALL_DIR="$FEAT_INSTALL_ROOT"
	SRC_DIR="$STELLA_APP_FEATURE_ROOT/$FEAT_NAME-$FEAT_VERSION-src"

	__get_resource "$FEAT_NAME" "$FEAT_SOURCE_URL" "$FEAT_SOURCE_URL_PROTOCOL" "$SRC_DIR" "DEST_ERASE FORCE_NAME $FEAT_SOURCE_URL_FILENAME"

	__set_toolset "STANDARD"

	AUTO_INSTALL_CONF_FLAG_PREFIX=
	AUTO_INSTALL_CONF_FLAG_POSTFIX=
	AUTO_INSTALL_BUILD_FLAG_PREFIX=
	AUTO_INSTALL_BUILD_FLAG_POSTFIX=

	__auto_build "$FEAT_NAME" "$SRC_DIR" "$INSTALL_DIR" "NO_CONFIG NO_INSTALL SOURCE_KEEP"

	__copy_folder_content_into "$SRC_DIR" "$INSTALL_DIR"

	__del_folder "$SRC_DIR"
}

fi
