if [ ! "$_jansson_INCLUDED_" = "1" ]; then
_jansson_INCLUDED_=1


feature_jansson() {
	FEAT_NAME=jansson
	FEAT_LIST_SCHEMA="2_11:source"
	FEAT_DEFAULT_ARCH=x64
	FEAT_DEFAULT_FLAVOUR="source"

	FEAT_DESC="C library for encoding, decoding and manipulating JSON data"
	FEAT_LINK="https://github.com/akheron/jansson"
}




feature_jansson_2_11() {
	FEAT_VERSION=2_11

	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL="https://github.com/akheron/jansson/archive/v2.11.tar.gz"
	FEAT_SOURCE_URL_FILENAME="jansson-v2.11.tar.gz"
	FEAT_SOURCE_URL_PROTOCOL="HTTP_ZIP"

	FEAT_BINARY_URL=
	FEAT_BINARY_URL_FILENAME=
	FEAT_BINARY_URL_PROTOCOL=


	FEAT_SOURCE_CALLBACK=
	FEAT_BINARY_CALLBACK=

	FEAT_ENV_CALLBACK=


	FEAT_INSTALL_TEST=$FEAT_INSTALL_ROOT/lib/libjansson.a
	FEAT_SEARCH_PATH=

}


feature_jansson_install_source() {
	INSTALL_DIR="$FEAT_INSTALL_ROOT"
	SRC_DIR="$STELLA_APP_FEATURE_ROOT/$FEAT_NAME-$FEAT_VERSION-src"

	__set_toolset "CMAKE"

	__get_resource "$FEAT_NAME" "$FEAT_SOURCE_URL" "$FEAT_SOURCE_URL_PROTOCOL" "$SRC_DIR" "DEST_ERASE STRIP FORCE_NAME $FEAT_SOURCE_URL_FILENAME"

	AUTO_INSTALL_CONF_FLAG_PREFIX=
	AUTO_INSTALL_CONF_FLAG_POSTFIX=
	AUTO_INSTALL_BUILD_FLAG_PREFIX=
	AUTO_INSTALL_BUILD_FLAG_POSTFIX=


	__auto_build "$FEAT_NAME" "$SRC_DIR" "$INSTALL_DIR"

}




fi
