if [ ! "$_lua_INCLUDED_" = "1" ]; then
_lua_INCLUDED_=1


feature_lua() {
	FEAT_NAME=lua
	FEAT_LIST_SCHEMA="5_3_2:source"
	FEAT_DEFAULT_ARCH=
	FEAT_DEFAULT_FLAVOUR="source"
}

feature_lua_5_3_2() {
	FEAT_VERSION=5_3_2


	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL=http://www.lua.org/ftp/lua-5.3.2.tar.gz
	FEAT_SOURCE_URL_FILENAME=lua-5.3.2.tar.gz
	FEAT_SOURCE_URL_PROTOCOL=HTTP_ZIP

	FEAT_BINARY_URL=
	FEAT_BINARY_URL_FILENAME=
	FEAT_BINARY_URL_PROTOCOL=

	FEAT_SOURCE_CALLBACK=
	FEAT_BINARY_CALLBACK=
	FEAT_ENV_CALLBACK=

	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT"/bin/lua
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"/bin

}



feature_lua_install_source() {
	INSTALL_DIR="$FEAT_INSTALL_ROOT"
	SRC_DIR="$STELLA_APP_FEATURE_ROOT/$FEAT_NAME-$FEAT_VERSION-src"

	__get_resource "$FEAT_NAME" "$FEAT_SOURCE_URL" "$FEAT_SOURCE_URL_PROTOCOL" "$SRC_DIR" "DEST_ERASE STRIP"

	__set_toolset "STANDARD"
	__set_build_mode "PARALLELIZE" "OFF"

	AUTO_INSTALL_CONF_FLAG_PREFIX=
	AUTO_INSTALL_CONF_FLAG_POSTFIX=
	AUTO_INSTALL_BUILD_FLAG_PREFIX=
	[ "$STELLA_CURRENT_PLATFORM" = "darwin" ] && AUTO_INSTALL_BUILD_FLAG_POSTFIX="macosx test install INSTALL_TOP=$INSTALL_DIR"
	[ "$STELLA_CURRENT_PLATFORM" = "linux" ] && AUTO_INSTALL_BUILD_FLAG_POSTFIX="linux test install INSTALL_TOP=$INSTALL_DIR"


	__auto_build "$FEAT_NAME" "$SRC_DIR" "$INSTALL_DIR" "NO_CONFIG NO_INSTALL"

}


fi
