if [ ! "$_kafka_INCLUDED_" = "1" ]; then
_kafka_INCLUDED_=1



feature_kafka() {
	FEAT_NAME=kafka
	FEAT_LIST_SCHEMA="0_10_0_1:binary 0_9_0_1:binary"
	FEAT_DEFAULT_ARCH=
	FEAT_DEFAULT_FLAVOUR="binary"
}


feature_kafka_0_10_0_1() {
	FEAT_VERSION=0_10_0_1
	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL=
	FEAT_SOURCE_URL_FILENAME=
	FEAT_SOURCE_URL_PROTOCOL=

	FEAT_BINARY_URL=https://archive.apache.org/dist/kafka/0.10.0.1/kafka_2.11-0.10.0.1.tgz
	FEAT_BINARY_URL_FILENAME=kafka_2.11-0.10.0.1.tgz
	FEAT_BINARY_URL_PROTOCOL=HTTP_ZIP

	FEAT_SOURCE_CALLBACK=
	FEAT_BINARY_CALLBACK=
	FEAT_ENV_CALLBACK=


	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT"/bin/kafka-server-start.sh
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"/bin

}


feature_kafka_0_9_0_1() {
	FEAT_VERSION=0_9_0_1
	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL=
	FEAT_SOURCE_URL_FILENAME=
	FEAT_SOURCE_URL_PROTOCOL=

	FEAT_BINARY_URL=https://archive.apache.org/dist/kafka/0.9.0.1/kafka_2.11-0.9.0.1.tgz
	FEAT_BINARY_URL_FILENAME=kafka_2.11-0.9.0.1.tgz
	FEAT_BINARY_URL_PROTOCOL=HTTP_ZIP

	FEAT_SOURCE_CALLBACK=
	FEAT_BINARY_CALLBACK=
	FEAT_ENV_CALLBACK=


	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT"/bin/kafka-server-start.sh
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"/bin

}

feature_kafka_install_binary() {
	__get_resource "$FEAT_NAME" "$FEAT_BINARY_URL" "$FEAT_BINARY_URL_PROTOCOL" "$FEAT_INSTALL_ROOT" "STRIP"

}


fi
