if [ ! "$_flink_INCLUDED_" = "1" ]; then
_flink_INCLUDED_=1


# need java

feature_flink() {
	FEAT_NAME=flink
	FEAT_LIST_SCHEMA="1_1_2_HADOOP_2_4:binary 0_10_1_HADOOP_2_4:binary"
	FEAT_DEFAULT_ARCH=
	FEAT_DEFAULT_FLAVOUR="binary"
}



feature_flink_1_1_2_HADOOP_2_4() {
	FEAT_VERSION=1_1_2_HADOOP_2_4
	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL=
	FEAT_SOURCE_URL_FILENAME=
	FEAT_SOURCE_URL_PROTOCOL=


	FEAT_BINARY_URL=http://archive.apache.org/dist/flink/flink-1.1.2/flink-1.1.2-bin-hadoop24-scala_2.11.tgz
	FEAT_BINARY_URL_FILENAME=flink-1.1.2-bin-hadoop24-scala_2.11.tgz
	FEAT_BINARY_URL_PROTOCOL=HTTP_ZIP

	FEAT_SOURCE_CALLBACK=
	FEAT_BINARY_CALLBACK=
	FEAT_ENV_CALLBACK=


	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT"/bin/flink
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"/bin

}

feature_flink_0_10_1_HADOOP_2_4() {
	FEAT_VERSION=0_10_1_HADOOP_2_4
	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL=
	FEAT_SOURCE_URL_FILENAME=
	FEAT_SOURCE_URL_PROTOCOL=

	FEAT_BINARY_URL=http://archive.apache.org/dist/flink/flink-0.10.1/flink-0.10.1-bin-hadoop24-scala_2.11.tgz
	FEAT_BINARY_URL_FILENAME=flink-0.10.1-bin-hadoop24-scala_2.11.tgz
	FEAT_BINARY_URL_PROTOCOL=HTTP_ZIP

	FEAT_SOURCE_CALLBACK=
	FEAT_BINARY_CALLBACK=
	FEAT_ENV_CALLBACK=


	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT"/bin/flink
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"/bin

}

feature_flink_install_binary() {
	__get_resource "$FEAT_NAME" "$FEAT_BINARY_URL" "$FEAT_BINARY_URL_PROTOCOL" "$FEAT_INSTALL_ROOT" "STRIP"

}


fi
