if [ ! "$_DASH_INCLUDED_" = "1" ]; then
_DASH_INCLUDED_=1


feature_dash() {
	FEAT_NAME=dash

	FEAT_LIST_SCHEMA="0_5_10_2:source 0_5_8:source"
	FEAT_DEFAULT_ARCH=
	FEAT_DEFAULT_FLAVOUR="source"


}


feature_dash_0_5_10_2() {
	FEAT_VERSION=0_5_10_2


	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL=http://gondor.apana.org.au/~herbert/dash/files/dash-0.5.10.2.tar.gz
	FEAT_SOURCE_URL_FILENAME=dash-0.5.10.2.tar.gz
	FEAT_SOURCE_URL_PROTOCOL=HTTP_ZIP

	FEAT_BINARY_URL=
	FEAT_BINARY_URL_FILENAME=
	FEAT_BINARY_URL_PROTOCOL=

	FEAT_SOURCE_CALLBACK=
	FEAT_BINARY_CALLBACK=
	FEAT_ENV_CALLBACK=

	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT"/bin/dash
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"/bin

}

feature_dash_0_5_8() {
	FEAT_VERSION=0_5_8


	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL=http://gondor.apana.org.au/~herbert/dash/files/dash-0.5.8.tar.gz
	FEAT_SOURCE_URL_FILENAME=dash-0.5.8.tar.gz
	FEAT_SOURCE_URL_PROTOCOL=HTTP_ZIP

	FEAT_BINARY_URL=
	FEAT_BINARY_URL_FILENAME=
	FEAT_BINARY_URL_PROTOCOL=

	FEAT_SOURCE_CALLBACK=
	FEAT_BINARY_CALLBACK=
	FEAT_ENV_CALLBACK=

	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT"/bin/dash
	FEAT_SEARCH_PATH="$FEAT_INSTALL_ROOT"/bin

}


feature_dash_install_source() {
	INSTALL_DIR="$FEAT_INSTALL_ROOT"
	SRC_DIR="$STELLA_APP_FEATURE_ROOT/$FEAT_NAME-$FEAT_VERSION-src"

	__set_toolset "STANDARD"

	__get_resource "$FEAT_NAME" "$FEAT_SOURCE_URL" "$FEAT_SOURCE_URL_PROTOCOL" "$SRC_DIR" "DEST_ERASE STRIP"


	AUTO_INSTALL_CONF_FLAG_PREFIX=
	AUTO_INSTALL_CONF_FLAG_POSTFIX="--disable-dependency-tracking \
						--with-libedit \
						--enable-fnmatch \
            --enable-glob"
	AUTO_INSTALL_BUILD_FLAG_PREFIX=
	AUTO_INSTALL_BUILD_FLAG_POSTFIX=

	__auto_build "$FEAT_NAME" "$SRC_DIR" "$INSTALL_DIR"


}


fi
