if [ ! "$_LIBSQUISH_INCLUDED_" = "1" ]; then
_LIBSQUISH_INCLUDED_=1

feature_libsquish() {
	FEAT_NAME=libsquish
	FEAT_LIST_SCHEMA="1_13:source"
	FEAT_DEFAULT_ARCH=
	FEAT_DEFAULT_FLAVOUR="source"
}

feature_libsquish_1_13() {
	FEAT_VERSION=1_13


	FEAT_SOURCE_DEPENDENCIES=
	FEAT_BINARY_DEPENDENCIES=

	FEAT_SOURCE_URL=http://downloads.sourceforge.net/project/libsquish/libsquish-1.13.tgz
	FEAT_SOURCE_URL_FILENAME=libsquish-1.13.tgz
	FEAT_SOURCE_URL_PROTOCOL=HTTP_ZIP

	FEAT_BINARY_URL=
	FEAT_BINARY_URL_FILENAME=
	FEAT_BINARY_URL_PROTOCOL=

	FEAT_SOURCE_CALLBACK=
	FEAT_BINARY_CALLBACK=
	FEAT_ENV_CALLBACK=

	FEAT_INSTALL_TEST="$FEAT_INSTALL_ROOT"/include/squish.h
	FEAT_SEARCH_PATH=

}



feature_libsquish_install_source() {
	INSTALL_DIR="$FEAT_INSTALL_ROOT"
	SRC_DIR="$STELLA_APP_FEATURE_ROOT/$FEAT_NAME-$FEAT_VERSION-src"

	__set_toolset "CMAKE"

	__get_resource "$FEAT_NAME" "$FEAT_SOURCE_URL" "$FEAT_SOURCE_URL_PROTOCOL" "$SRC_DIR" "DEST_ERASE"

	AUTO_INSTALL_CONF_FLAG_PREFIX=
	# -DBUILD_SQUISH_WITH_ALTIVEC=ON for powerpc
	AUTO_INSTALL_CONF_FLAG_POSTFIX="-DBUILD_SQUISH_WITH_SSE2=ON -DBUILD_SQUISH_WITH_ALTIVEC=OFF -DBUILD_SHARED_LIBS=ON -DBUILD_SQUISH_EXTRA=OFF"
	AUTO_INSTALL_BUILD_FLAG_PREFIX=
	AUTO_INSTALL_BUILD_FLAG_POSTFIX=
	__auto_build "$FEAT_NAME" "$SRC_DIR" "$INSTALL_DIR" "SOURCE_KEEP"


	AUTO_INSTALL_CONF_FLAG_POSTFIX="-DBUILD_SQUISH_WITH_SSE2=ON -DBUILD_SQUISH_WITH_ALTIVEC=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_SQUISH_EXTRA=OFF"
	__auto_build "$FEAT_NAME" "$SRC_DIR" "$INSTALL_DIR"


}


fi
