name: Continuous Integration

on: 
  push:
    tags:
    - '*'
jobs:
    ci:
        name: build and release docker plugin
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v2
          - name: determine image version tag
            id: image_tag
            run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          - name: build plugin
            run: make BINDFS_VERSION=1_13_11 PLUGIN_TAG=latest all
          - name: build a plugin version for ghcr
            run: make PLUGIN_TAG=latest create-plugin-ghcr
          - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Login to Github Packages
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
          - name: Push
            run: |
              docker plugin push ghcr.io/studioetrange/bindfs:latest
              docker plugin push studioetrange/bindfs:latest