name: Continuous Integration

on: 
  push:
    tags:
    - '*'
jobs:
    ci:
        name: build and release docker images
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v2
          - name: determine image version tag
            id: image_tag
            run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          - name: build docker image
            run: make BINDFS_VERSION=1_13_11 PLUGIN_TAG=${{ steps.image_tag.outputs.tag }} all
          - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Login to Github Packages
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
          - name: Push
            run: |
              docker push ghcr.io/studioetrange/bindfs:${{ steps.image_tag.outputs.tag }}
              docker push studioetrange/bindfs:${{ steps.image_tag.outputs.tag }}